### PR TITLE
Remove deprecated package feature

### PR DESCRIPTION
**Pull request by snapshotpl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Removed build and deployment package because https://github.com/zfcampus/zf-deploy is abandoned. Via suggestion https://github.com/laminas-api-tools/api-tools-admin/pull/85#issuecomment-1147490314

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
OK for me, but target branch will be `2.0.x` then

**Comment by snapshotpl** [comment]
I created `2.0.x` manually

**Review by Ocramius — CHANGES_REQUESTED** [review]
We will need to adjust `composer.json` to prevent installations with `laminas-api-tools/api-tools-admin:^1`, since it will be incompatible.

Ref: https://github.com/laminas-api-tools/api-tools-admin/pull/85

**Comment by Ocramius** [comment]
`laminas-api-tools/api-tools-admin:2.0.0` is out: let's update this and then we can merge+release here too :+1:

**Comment by snapshotpl** [comment]
You have release `laminas-api-tools/api-tools-admin` too fast. `laminas-api-tools/api-tools-admin` requires `laminas-api-tools/api-tools-admin-ui` so this pull request should be first merge and release :thinking:

**Comment by Ocramius** [comment]
This is the consumer of `laminas-api-tools/api-tools-admin`, no? :thinking: 

I can certainly fix up a patch release afterwards, if you want: not really too fussed about it.

**Comment by Ocramius** [comment]
Urgh, it is the other way around indeed -.-

https://github.com/laminas-api-tools/api-tools-admin/blob/6c97eaea05d6d228281ae3b70d8d65a5757c9dd3/composer.json#L35

My bad, guess `2.1.0` of `laminas-api-tools/api-tools-admin` will have to happen too :-\

**Comment by snapshotpl** [comment]
```
$ composer require laminas-api-tools/api-tools-admin:2.0.0
./composer.json has been updated
Running composer update laminas-api-tools/api-tools-admin
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laminas-api-tools/api-tools-admin 2.0.0 -> satisfiable by laminas-api-tools/api-tools-admin[2.0.0].
    - laminas-api-tools/api-tools-admin 2.0.0 requires laminas-api-tools/api-tools-admin-ui ^1.3.9 -> satisfiable by laminas-api-tools/api-tools-admin-ui[1.3.9, ..., 1.6.x-dev] from composer repo (https://repo.packagist.org) but laminas-api-tools/api-tools-admin-ui is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.
```

**Comment by Ocramius** [comment]
Yeah, chicken-egg :-\ 

It's super weird that this package is set as a dependency of the server-side one though, when this one is the consumer.

**Comment by Ocramius** [comment]
OK, I think we just require the newer release of this package in `laminas-api-tools/api-tools-admin`, rather than messing with `composer.json` here.

Overall, my feeling is that this package should be merged into `laminas-api-tools/api-tools-admin`, instead of developed separately.

**Comment by snapshotpl** [comment]
IMO First option is better for now. So need to release this package as `2.0.0` and then require it in `laminas-api-tools/api-tools-admin` as patch?

**Comment by Ocramius** [comment]
Absolutely, that sounds correct.

The entire "merge it into the other project" was just me thinking aloud, since it could be a better long-term strategy.

**Comment by snapshotpl** [comment]
So can I merge and release this one?

**Review by Ocramius — APPROVED** [review]
Yup, lemme go ahead and do that :+1: 

Thanks @snapshotpl!

**Comment by Ocramius** [comment]
@snapshotpl now released :+1:

**Pull request merged**
